In [10]:
import numpy as np

M = np.array(
    [
        [2,3], 
        [5, -8]
    ]
)
N = np.array(
    [
        [1, -4],
        [8, -6]
    ]
)

print('M+N = ', M+N)
print('M*N =', M*N)
print('M@N =', M@N)
print('M.dot(N) =', M.dot(N))
print('The transpose of M is: ', np.transpose(M))

M+N =  [[  3  -1]
 [ 13 -14]]
M*N = [[  2 -12]
 [ 40  48]]
M@N = [[ 26 -26]
 [-59  28]]
M.dot(N) = [[ 26 -26]
 [-59  28]]
The transpose of M is:  [[ 2  5]
 [ 3 -8]]


# 3.2 Numpy.linalg

2
© 2019, 2022 University of Hertfordshire Higher Education Corporation
numpy.linalg is a class having a standard set of things like inverse, determinant
and matrix decompositions, You need to import numpy.linalg first:
Task1:
1) compute the inverse of the matrix M defined in 3.1 using LA.inv(𝑀).
2) compute the determinant of matrix N defined in 3.1 using LA.det(𝑀)

In [2]:
import numpy as np
import numpy.linalg as LA
M = np.array(
    [
        [2, 3], 
        [5, -8]
    ]
)


inverse_M = LA.inv(M)
print(inverse_M)

det_M = LA.det(M)
print(det_M)

[[ 0.25806452  0.09677419]
 [ 0.16129032 -0.06451613]]
-31.0


In [17]:
import numpy as np
import numpy.linalg as LA

A = np.array(
    [
        [3, 1, 2],
        [1, 4, 0],
        [2, 0, 5]
    ]
)
print(A)
print()
eignVal,eignVec = LA.eig(A)
print('eignVal \n & eignVec \n = ', eignVal,eignVec)



dot_M = np.dot(eignVec, eignVal.T)
print()
print('dot of M= ', dot_M)

[[3 1 2]
 [1 4 0]
 [2 0 5]]

eignVal 
 & eignVec 
 =  [1.47108204 6.36146877 4.16744919] [[ 0.8226726  -0.54739786 -0.15351016]
 [-0.32530617 -0.23180398 -0.91675668]
 [-0.46624638 -0.80412841  0.36877068]]

dot of M=  [-2.91178129 -5.77370273 -4.26449136]


In [18]:
x4 = np.array(
    [10, 9, -1, 3]
)

x4

array([10,  9, -1,  3])

In [19]:
np.sort(x4)

array([-1,  3,  9, 10])

In [20]:
np.sort(x4) [::-1]

array([10,  9,  3, -1])